# Minimal iOS / Simulator toolchain for OrcaSlicer engine (no wx GUI).
# Usage:
#   cmake -S . -B build-ios-iphonesimulator-arm64 \
#     -DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
#     -DPLATFORM=OS64SIMULATOR ...

if(NOT DEFINED PLATFORM)
  set(PLATFORM "OS64SIMULATOR")
endif()

if(PLATFORM STREQUAL "OS64" OR PLATFORM STREQUAL "OS")
  set(CMAKE_SYSTEM_NAME iOS)
  set(CMAKE_OSX_SYSROOT iphoneos)
  set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "" FORCE)
  set(IOS_DEPLOYMENT_TARGET "16.0" CACHE STRING "")
elseif(PLATFORM STREQUAL "OS64SIMULATOR" OR PLATFORM STREQUAL "SIMULATOR64" OR PLATFORM STREQUAL "SIMULATORARM64")
  set(CMAKE_SYSTEM_NAME iOS)
  set(CMAKE_OSX_SYSROOT iphonesimulator)
  set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "" FORCE)
  set(IOS_DEPLOYMENT_TARGET "16.0" CACHE STRING "")
else()
  message(FATAL_ERROR "Unknown PLATFORM=${PLATFORM}. Use OS64 or OS64SIMULATOR")
endif()

set(CMAKE_OSX_DEPLOYMENT_TARGET "${IOS_DEPLOYMENT_TARGET}" CACHE STRING "" FORCE)
set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO)
set(CMAKE_CROSSCOMPILING TRUE)
set(ORCA_IOS ON CACHE BOOL "iOS port" FORCE)

# Find programs on host
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

message(STATUS "Orca iOS toolchain: PLATFORM=${PLATFORM} SYSROOT=${CMAKE_OSX_SYSROOT} ARCH=${CMAKE_OSX_ARCHITECTURES}")
